language: rust

rust: 
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

# deploy:
#   provider: script
#   script: scripts/master.sh
#   on:
#     tags: true
#     branch: master